"""rename hashed_jti to jti

Revision ID: 34949d1e0127
Revises: 58bc773e47a7
Create Date: 2025-03-29 13:12:34.278245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34949d1e0127'
down_revision: Union[str, None] = '58bc773e47a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_refresh_tokens', sa.Column('jti', sa.String(), nullable=False))
    op.drop_index('idx_user_hashed_jti', table_name='blacklist_refresh_tokens')
    op.create_index('idx_user_hashed_jti', 'blacklist_refresh_tokens', ['user_id', 'jti'], unique=False)
    op.drop_column('blacklist_refresh_tokens', 'hashed_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_refresh_tokens', sa.Column('hashed_jti', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('idx_user_hashed_jti', table_name='blacklist_refresh_tokens')
    op.create_index('idx_user_hashed_jti', 'blacklist_refresh_tokens', ['user_id', 'hashed_jti'], unique=False)
    op.drop_column('blacklist_refresh_tokens', 'jti')
    # ### end Alembic commands ###
