"""Added task and user

Revision ID: b72f65217ca8
Revises: e22284faf60b
Create Date: 2024-12-29 21:10:44.177010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72f65217ca8'
down_revision: Union[str, None] = 'e22284faf60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column with a default value of True
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # Remove the default constraint after existing rows are updated
    op.alter_column('users', 'is_active', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
